name: Bug Report 🐛
description: Signaler un bug pour nous aider à améliorer l'application.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de signaler ce bug ! 🍻
  - type: textarea
    id: bug-description
    attributes:
      label: Description du bug
      description: Une description claire et concise du bug rencontré.
      placeholder: "Ce qui se passe..."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Étapes pour reproduire
      description: Comment pouvons-nous reproduire le bug ?
      placeholder: |
        1. Allez sur '...'
        2. Cliquez sur '....'
        3. Voir l'erreur
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Comportement attendu
      description: Ce qui devrait normalement se passer.
  - type: input
    id: environment
    attributes:
      label: Environnement
      description: Émulateur, version Android, etc.
      placeholder: "Android 14, Émulateur Pixel 7"
