name: Feature Request 🚀
description: Proposer une nouvelle idée ou une amélioration.
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Description de la fonctionnalité
      description: Quelle nouvelle fonctionnalité aimeriez-vous voir ?
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Pourquoi est-ce utile ?
      description: En quoi cela aidera-t-il les gérants de maquis ?
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives envisagées
      description: Avez-vous pensé à d'autres solutions ?
